const data = {
  projects: [
    {
      key: 0,
      projectName: "Tonic",
      companyName: "CANOPY",
      projectCounterIcon: "images/Counter.svg",
      projectImage: "images/Snapshoot Portfolio1.svg",
      projectPosition: "Back End Dev",
      projectDate: "2015",
      projectTechHtml: "html",
      projecttechCss: "csss",
      projectTechJs: "Javascript",
      projectDescription: `A daily selection of privately personalized reads; no accounts or
            sign-ups required.`,
      liveLink: "#",
      sourceLink: "3",
      seeProjectBtnText: "See Project",
    },
    {
      key: 1,
      projectName: "Multi-Post Stories",
      companyName: "CANOPY",
      projectCounterIcon: "images/Counter.svg",
      projectImage: "images/Snapshoot Portfolio2.svg",
      projectPosition: "Back End Dev",
      projectDate: "2015",
      projectTechHtml: "html",
      projecttechCss: "csss",
      projectTechJs: "Javascript",
      projectDescription: `A daily selection of privately personalized reads; no accounts or
            sign-ups required.`,
      liveLink: "#",
      sourceLink: "3",
      seeProjectBtnText: "See Project",
    },
    {
      key: 2,
      projectName: "Tonic",
      companyName: "CANOPY",
      projectCounterIcon: "images/Counter.svg",
      projectImage: "images/Snapshoot Portfolio3.svg",
      projectPosition: "Back End Dev",
      projectDate: "2015",
      projectTechHtml: "html",
      projecttechCss: "csss",
      projectTechJs: "Javascript",
      projectDescription: `A daily selection of privately personalized reads; no accounts or
            sign-ups required.`,
      liveLink: "#",
      sourceLink: "3",
      seeProjectBtnText: "See Project",
    },
    {
      key: 3,
      projectName: "Multi-Post Stories",
      companyName: "CANOPY",
      projectCounterIcon: "images/Snapshoot Portfolio4.svg",
      projectImage: "images/Snapshoot Portfolio4.svg",
      projectPosition: "Back End Dev",
      projectDate: "2015",
      projectTechHtml: "html",
      projecttechCss: "csss",
      projectTechJs: "Javascript",
      projectDescription: `A daily selection of privately personalized reads; no accounts or
            sign-ups required.`,
      liveLink: "#",
      sourceLink: "3",
      seeProjectBtnText: "See Project",
    },
  ],
};

export default data;